import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'bg-primary': '#F7F8FA',
        'bg-secondary': '#F0F1F3',
        surface: '#FFFFFF',
        'surface-hover': '#F3F4F6',
        'surface-elevated': '#FFFFFF',
        primary: '#2B6CB0',
        'primary-hover': '#1A4F8A',
        'primary-active': '#0F3A6B',
        'primary-subtle': '#EBF1FA',
        'gray-50': '#F9FAFB',
        'gray-100': '#F3F4F6',
        'gray-200': '#E5E7EB',
        'gray-300': '#D1D5DB',
        'gray-400': '#9CA3AF',
        'gray-500': '#6B7280',
        'gray-600': '#4B5563',
        'gray-700': '#374151',
        'gray-800': '#1F2937',
        'gray-900': '#111827',
        danger: '#DC2626',
        'danger-bg': '#FEF2F2',
        warning: '#D97706',
        'warning-bg': '#FFFBEB',
        success: '#059669',
        'success-bg': '#ECFDF5',
        idle: '#9CA3AF',
        'idle-bg': '#F3F4F6',
        info: '#2563EB',
        'info-bg': '#EFF6FF',
        'masked-bg': '#F3F4F6',
        'masked-text': '#9CA3AF',
        'text-primary': '#1F2937',
        'text-secondary': '#6B7280',
        'text-tertiary': '#9CA3AF',
        border: '#E5E7EB',
        'border-strong': '#D1D5DB',
        divider: '#F0F1F3',
      },
      fontFamily: {
        sans: ["'Inter'", '-apple-system', 'BlinkMacSystemFont', "'Segoe UI'", 'sans-serif'],
        mono: ["'JetBrains Mono'", "'SF Mono'", "'Fira Code'", "'Menlo'", 'monospace'],
      },
      spacing: {
        '2xs': '4px',
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '20px',
        xl: '24px',
        '2xl': '32px',
        '3xl': '48px',
        '4xl': '64px',
      },
      borderRadius: {
        sm: '4px',
        md: '6px',
        lg: '8px',
        xl: '12px',
        pill: '16px',
      },
      boxShadow: {
        none: 'none',
        sm: '0 1px 2px rgba(0,0,0,0.05)',
        md: '0 4px 6px rgba(0,0,0,0.07)',
        lg: '0 10px 15px rgba(0,0,0,0.1)',
        xl: '0 20px 40px rgba(0,0,0,0.15)',
        sticky: '0 1px 3px rgba(0,0,0,0.08)',
      },
    },
  },
  plugins: [],
};

export default config;
